DROP TABLE IF EXISTS UPE_PENDING;
DROP TABLE IF EXISTS UPE_USER;

CREATE TABLE UPE_USER (
    USER_ID    INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
    USERNAME   VARCHAR(20)       NOT NULL,
    PASSWORD   CHAR(40)          NOT NULL,
    EMAIL_ADDR VARCHAR(100)      NOT NULL,
    IS_ACTIVE  TINYINT(1)        DEFAULT 0,
	USER_PRIV  TINYINT(1)        DEFAULT 0,
    PRIMARY KEY (USER_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs AUTO_INCREMENT=0;

CREATE TABLE UPE_PENDING (
    USER_ID       INTEGER UNSIGNED  NOT NULL,
    TOKEN         CHAR(10)          NOT NULL,
    CREATED_DATE  TIMESTAMP         DEFAULT  CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID)
        REFERENCES WROX_USER(USER_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs;

CREATE TABLE UPE_INVEST (
    USER_ID    INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
	SCORE1     INTEGER UNSIGNED  NOT NULL  DEFAULT 0,
	SCORE2     INTEGER UNSIGNED  NOT NULL  DEFAULT 0,
	SCORE3     INTEGER UNSIGNED  NOT NULL  DEFAULT 0,
	SCORE4     INTEGER UNSIGNED  NOT NULL  DEFAULT 0,
	CASH1      INTEGER UNSIGNED  NOT NULL  DEFAULT 0,
	CASH2      INTEGER UNSIGNED  NOT NULL  DEFAULT 0,
	CASH3      INTEGER UNSIGNED  NOT NULL  DEFAULT 0,
	CASH4      INTEGER UNSIGNED  NOT NULL  DEFAULT 0,
    PRIMARY KEY (USER_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs AUTO_INCREMENT=0;


CREATE TABLE UPE_TASK (
    TASK_ID    INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
	TASK_TYPE  CHAR(10)          NOT NULL,
	TASK_INFO  CHAR(100)         NOT NULL,
	TASK_SCORE INTEGER UNSIGNED  NOT NULL,
	TASK_PRIV  INTEGER UNSIGNED  NOT NULL,
	TASK_STAT  CHAR(1)           NOT NULL DEFAULT 'p',
	TASK_START DATE         	 NOT NULL,
	TASK_STOP  DATE              NOT NULL,
	TASK_MANAGER CHAR(20)        NOT NULL,
	TASK_MEMBER  CHAR(50)        NOT NULL,
	TASK_NOTE	 CHAR(100)       NOT NULL,
    PRIMARY KEY (TASK_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs AUTO_INCREMENT=0;



INSERT INTO UPE_USER (USER_ID, USERNAME, PASSWORD, IS_ACTIVE, USER_PRIV) VALUES 
('1', 'licaijun', 'f7c3bc1d808e04732adf679965ccc34ca7ae3441', '1', '1');
INSERT INTO UPE_USER (USER_ID, USERNAME, PASSWORD, IS_ACTIVE, USER_PRIV) VALUES 
('2', 'linzhian', 'f7c3bc1d808e04732adf679965ccc34ca7ae3441', '1', '0');
INSERT INTO UPE_USER (USER_ID, USERNAME, PASSWORD, IS_ACTIVE, USER_PRIV) VALUES 
('3', 'zengjianhua', 'f7c3bc1d808e04732adf679965ccc34ca7ae3441', '1', '0');
